language: node_js
sudo: required
before_install:
  # Install Syncthing
  - curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
  - echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list
  - sudo apt-get update -qq
  - sudo apt-get install syncthing -y -qq
  - cd test
  - echo "Hello World" > test.txt
  - mkdir random-folder
  - syncthing -home . -no-browser &
node_js:
  - "6.3.0"
before_script:
  - "npm install"
  - "npm run build"
script:
  - "npm test"
cache:
  directories:
    - node_modules
