language: node_js
sudo: required
before_install:
  # Install Syncthing
  - curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
  - echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list
  - sudo apt-get update -qq
  - sudo apt-get install syncthing -y -qq
  - mkdir $HOME/Sync
  - echo "Test" > $HOME/Sync/test.txt
node_js:
  - "5.3.0"
before_script:
  - sudo ls /etc/init.d
  - sudo /etc/init.d/syncthing stop
  - sudo /etc/init.d/syncthing start
  - "npm install"
  - "npm run build"
script:
  - "npm test"
cache:
  directories:
    - node_modules
