language: node_js
sudo: required
before_install:
  # Install Syncthing
  - curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
  - echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list
  - sudo apt-get update -qq
  - sudo apt-get install syncthing -y -qq
  - mkdir $HOME/Sync
  - echo "Test" > $HOME/Sync/test.txt
  - sudo wget https://gist.githubusercontent.com/arudmin/5a13e9105814c3f568ec/raw/730c442936180620e2a715ac6e13498c37e571c4/syncthing -O /etc/init.d/syncthing
  - sudo chmod +x /etc/init.d/syncthing
  - sudo update-rc.d syncthing defaults
  - sudo /etc/init.d/syncthing stop
  - sudo /etc/init.d/syncthing start
node_js:
  - "5.3.0"
before_script:
  - "npm install"
  - "npm run build"
script:
  - "npm test"
cache:
  directories:
    - node_modules
